baseURL: /
theme: beth
title: Beth's Genealogy Site
languageCode: en-US
pygmentsCodeFences: true
pygmentsUseClasses: true
canonifyURLs: true
enableEmoji: true
enableRobotsTXT: true
paginate: 5
permalinks:
  posts: /posts/:slug/
  tags: /tags/:title/
  family: /family/:title/
  individuals: /individuals/:title/
taxonomies:
  tag: tags
  series: series
  individual: individuals
security:
  exec:
    osEnv:
      - '(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$'
      - ^ASDF_DIR$
      - ^HOME$
    allow:
    - ^asciidoctor