baseURL: "mbeckrich.github.io/genes"
theme: beth
title: "Family History & Stories"
languageCode: en-US
pygmentsCodeFences: true
pygmentsUseClasses: true
enableEmoji: true
enableRobotsTXT: true
paginate: 5
disablePathToLower: true
permalinks:
  posts: /posts/:slug
  individuals: /individuals/:slug
taxonomies:
  tag: tags
  series: series
  individual: individuals
security:
  exec:
    osEnv:
      - "(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$"
      - ^HOME$
    allow:
      - ^asciidoctor$
      - ^dart-sass-embedded$
