extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-idiomatic-order
ignore-files:
  - node_modules/**/*
plugins:
  - stylelint-order
  - stylelint-declaration-block-no-ignored-properties
rules:
  alpha-value-notation: percentage
  color-function-notation: modern
  declaration-property-value-no-unknown: true
  plugin/declaration-block-no-ignored-properties: true
