extends:
  - stylelint-config-html
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-idiomatic-order
ignore-files:
  - node_modules/**/*
plugins:
  - stylelint-order
rules:
  string-quotes: double
  selector-attribute-quotes: always
  alpha-value-notation: percentage
  color-function-notation: modern
