extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-idiomatic-order
ignore-files:
  - node_modules/**/*
plugins:
  - stylelint-order
  - stylelint-declaration-block-no-ignored-properties
rules:
  string-quotes: double
  selector-attribute-quotes: always
  alpha-value-notation: percentage
  color-function-notation: modern
  plugin/declaration-block-no-ignored-properties: true
